using Microsoft.VisualBasic.FileIO;
using System.Collections.Generic;
using System.IO;

namespace BuildQuestionInteractionData
{
	class Program
	{
		static void Main(string[] args)
		{

			var fictionalSchools = GetFictionalSchools();
			var schools = new Dictionary<string, string>();
			var output = new List<string>();

			using var parser = new TextFieldParser(@"D:\Repros\TaleLearnCode\Presentations\Ch-Ch-Ch-Changes\Demos\Data\QuestionInteractions.csv");
			parser.TextFieldType = FieldType.Delimited;
			parser.SetDelimiters(",");

			while (!parser.EndOfData)
			{
				string[] fields = parser.ReadFields();
				if (!schools.ContainsKey(fields[1]))
					schools.Add(fields[1], fictionalSchools[schools.Count + 1]);
				output.Add($"{fields[0]},{schools[fields[1]]}");
			}

			File.WriteAllLines(@"D:\Repros\TaleLearnCode\Presentations\Ch-Ch-Ch-Changes\Demos\Data\QuestionInteractions-New.csv", output);

		}


		static List<string> GetFictionalSchools()
		{
			var returnValue = new List<string>();
			returnValue.Add("Academy of Computer Sciences");
			returnValue.Add("Adams College");
			returnValue.Add("University of Albuquerque");
			returnValue.Add("All Systems University");
			returnValue.Add("Arlen Community College");
			returnValue.Add("Arlen University");
			returnValue.Add("Arlington University");
			returnValue.Add("Athena College");
			returnValue.Add("Atlanta A&T University");
			returnValue.Add("Atlantic State University");
			returnValue.Add("University of Austin");
			returnValue.Add("Bancroft College");
			returnValue.Add("Banting University");
			returnValue.Add("Barnett College");
			returnValue.Add("Belford College");
			returnValue.Add("Bending State College");
			returnValue.Add("Bikini Bottom Community College");
			returnValue.Add("Bikini Bottom University");
			returnValue.Add("Boatwright University");
			returnValue.Add("Boston Bay College");
			returnValue.Add("Bovine University");
			returnValue.Add("Bradbury University");
			returnValue.Add("Brichester University");
			returnValue.Add("Bridgeford University");
			returnValue.Add("Bristol College");
			returnValue.Add("Bromwell University");
			returnValue.Add("Cadwalader College");
			returnValue.Add("California University");
			returnValue.Add("California University of Los Angeles");
			returnValue.Add("CalSci");
			returnValue.Add("Calcutta Technical Institute");
			returnValue.Add("University of California at Sunnydale");
			returnValue.Add("Calvert College");
			returnValue.Add("Camden College");
			returnValue.Add("Camford University");
			returnValue.Add("Capeside Community College");
			returnValue.Add("Celadon University");
			returnValue.Add("Centerscore University Surviving High School Mobile Games");
			returnValue.Add("Charles University");
			returnValue.Add("Christminster University and Bibliol College");
			returnValue.Add("Chelsea University");
			returnValue.Add("Coney Island Community College");
			returnValue.Add("Copeland College");
			returnValue.Add("Coolidge College");
			returnValue.Add("Crandall College");
			returnValue.Add("Crazy Go Nuts University");
			returnValue.Add("Cyprus-Rhodes University");
			returnValue.Add("Culver University");
			returnValue.Add("Darwin College");
			returnValue.Add("Daystrom Institute");
			returnValue.Add("Dupont University");
			returnValue.Add("University of Edgestow");
			returnValue.Add("Eastern State University");
			returnValue.Add("Eden Hills University");
			returnValue.Add("University of Eaton");
			returnValue.Add("Emily Dickinson College");
			returnValue.Add("Empire State University");
			returnValue.Add("Enormous State University");
			returnValue.Add("Erdle College");
			returnValue.Add("Euphoric State University");
			returnValue.Add("Faber College");
			returnValue.Add("Fallcreek University");
			returnValue.Add("Globetrotter University");
			returnValue.Add("Gotham University");
			returnValue.Add("University of Gloucester");
			returnValue.Add("Genoa City University");
			returnValue.Add("George Underwood Edwards Institute of Technology");
			returnValue.Add("George Washington Carver University");
			returnValue.Add("Godolphin College");
			returnValue.Add("Goober State College");
			returnValue.Add("Grand Lakes University");
			returnValue.Add("Grant College");
			returnValue.Add("Grant University");
			returnValue.Add("Greendale Community College");
			returnValue.Add("Greenville Community College");
			returnValue.Add("Groff Community College");
			returnValue.Add("Hacker College");
			returnValue.Add("Hamilton University");
			returnValue.Add("Happy Duck University");
			returnValue.Add("Harmon College");
			returnValue.Add("Harrad College");
			returnValue.Add("Harrison University");
			returnValue.Add("Harry S Truman College");
			returnValue.Add("Hearst College");
			returnValue.Add("Heartland State University");
			returnValue.Add("Hill Valley College");
			returnValue.Add("Hillman College");
			returnValue.Add("Houston Tech");
			returnValue.Add("Hudson University");
			returnValue.Add("Huxley College");
			returnValue.Add("Illinois Poly");
			returnValue.Add("University of Ipswich");
			returnValue.Add("University of Ithaca");
			returnValue.Add("Ivy University");
			returnValue.Add("Jonan University");
			returnValue.Add("Jordan College - Oxford");
			returnValue.Add("Jordan College");
			returnValue.Add("Jupiter State");
			returnValue.Add("Katnip Kollege");
			returnValue.Add("Kennison State University");
			returnValue.Add("Langley College");
			returnValue.Add("University of Las Cruces");
			returnValue.Add("Leland College");
			returnValue.Add("Lone Star State");
			returnValue.Add("Llanview University");
			returnValue.Add("Los Angeles University");
			returnValue.Add("University of Los Angeles");
			returnValue.Add("University of Louisiana");
			returnValue.Add("Lowlands University");
			returnValue.Add("Magical Cloud Kingdom College");
			returnValue.Add("Mars University");
			returnValue.Add("Maguire University");
			returnValue.Add("Marshall College");
			returnValue.Add("Martha Graham Academy");
			returnValue.Add("Maumee Tech");
			returnValue.Add("Medfield College");
			returnValue.Add("Metropolis University");
			returnValue.Add("Mildew College");
			returnValue.Add("Middleton College");
			returnValue.Add("Midston University");
			returnValue.Add("Midvale College");
			returnValue.Add("Midwestern University");
			returnValue.Add("Minnesota State University");
			returnValue.Add("University of Minnetonka");
			returnValue.Add("Miskatonic University");
			returnValue.Add("Mission College");
			returnValue.Add("Monroe College");
			returnValue.Add("Muppet University");
			returnValue.Add("University of New York");
			returnValue.Add("University of North Alaska");
			returnValue.Add("University of North East California");
			returnValue.Add("North Southwestern State University");
			returnValue.Add("University of Okoboji");
			returnValue.Add("Ole Tex");
			returnValue.Add("Oxbridge University");
			returnValue.Add("Orange County University");
			returnValue.Add("Pacific Institute of Technology");
			returnValue.Add("Patrick Henry University");
			returnValue.Add("Pawlton College");
			returnValue.Add("Payton-Noble University");
			returnValue.Add("Pendelton University");
			returnValue.Add("Pendelton State University");
			returnValue.Add("Pennbrook University");
			returnValue.Add("Piermont College");
			returnValue.Add("Pine Valley University");
			returnValue.Add("Plainfield Teacher's College");
			returnValue.Add("Pomona University");
			returnValue.Add("University of Poppleton");
			returnValue.Add("Port Chester University");
			returnValue.Add("Potawotami College");
			returnValue.Add("Prinstone University");
			returnValue.Add("Rutland University");
			returnValue.Add("University of Quahog");
			returnValue.Add("Quendelton State University");
			returnValue.Add("Raft University");
			returnValue.Add("Rainier University");
			returnValue.Add("Ramsey University");
			returnValue.Add("Raytown Junior College");
			returnValue.Add("Randolph Harrington College");
			returnValue.Add("Ridgemont College");
			returnValue.Add("Robert Treat College");
			returnValue.Add("Rockland University");
			returnValue.Add("Rosemont University");
			returnValue.Add("University of Rummidge");
			returnValue.Add("Rumson University");
			returnValue.Add("San Francisco University");
			returnValue.Add("St. Anthony's College");
			returnValue.Add("Salem University");
			returnValue.Add("Santa Monica College");
			returnValue.Add("Saraswati Humanocentric Educlave and Research Institute");
			returnValue.Add("Scioto State");
			returnValue.Add("Scumbag College");
			returnValue.Add("University of Southern North Dakota at Hoople");
			returnValue.Add("Shale University");
			returnValue.Add("Shiz University");
			returnValue.Add("Siwash College");
			returnValue.Add("Smithdale University");
			returnValue.Add("South Central Louisiana State University");
			returnValue.Add("South Harmon Institute of Technology");
			returnValue.Add("Southern Atlantic University");
			returnValue.Add("Southern California State University");
			returnValue.Add("Springfield A & M");
			returnValue.Add("Springfield Community College");
			returnValue.Add("Springfield Heights Institute of Technology");
			returnValue.Add("Springfield University");
			returnValue.Add("The State College for Negroes");
			returnValue.Add("Stanhope College");
			returnValue.Add("Stansbury University");
			returnValue.Add("State College");
			returnValue.Add("State University");
			returnValue.Add("State University");
			returnValue.Add("Suffix University");
			returnValue.Add("University of Suffolk");
			returnValue.Add("University of California at Sunnydale");
			returnValue.Add("Sweet Valley University");
			returnValue.Add("Swigmore University");
			returnValue.Add("Tait College");
			returnValue.Add("Tate University");
			returnValue.Add("Tate University");
			returnValue.Add("Tekerson Tech");
			returnValue.Add("Texas A&F University");
			returnValue.Add("Texas Methodist University");
			returnValue.Add("Texas State University");
			returnValue.Add("Texas State University");
			returnValue.Add("Southwest Texas State");
			returnValue.Add("Trinity College");
			returnValue.Add("Trumaine University");
			returnValue.Add("Truth University");
			returnValue.Add("UCC");
			returnValue.Add("Underhill College");
			returnValue.Add("Underwater Sea Aqua College");
			returnValue.Add("University of the United States");
			returnValue.Add("Unknown University");
			returnValue.Add("Unseen University");
			returnValue.Add("Upton University");
			returnValue.Add("Uxbridge University");
			returnValue.Add("Vulcan Science Academy");
			returnValue.Add("University of Watermouth");
			returnValue.Add("University of Westfield");
			returnValue.Add("University of Winnemac");
			returnValue.Add("Waindell College");
			returnValue.Add("Walden College");
			returnValue.Add("Watson-Crick Institute");
			returnValue.Add("Watchers Academy");
			returnValue.Add("Wellington College");
			returnValue.Add("Wellman College");
			returnValue.Add("Wentbridge University");
			returnValue.Add("West Texas University");
			returnValue.Add("Western University");
			returnValue.Add("Wildstone University");
			returnValue.Add("Winesburg College");
			returnValue.Add("West Las Vegas University");
			returnValue.Add("Witch University");
			returnValue.Add("Wordsmith University");
			returnValue.Add("Worthington University");
			returnValue.Add("Wossamotta University");
			returnValue.Add("Xavier Institute for Higher Learning");
			returnValue.Add("Yippahoopy College");
			returnValue.Add("Cardinal's College");
			returnValue.Add("Foxe College");
			returnValue.Add("Gabriel College");
			returnValue.Add("Jordan College");
			returnValue.Add("Queen Philippa's College");
			returnValue.Add("St Michael's College");
			returnValue.Add("St Scholastica's College");
			returnValue.Add("St Sophia's College");
			returnValue.Add("Wordsworth College");
			returnValue.Add("Wykeham College");
			returnValue.Add("Alfreda's College");
			returnValue.Add("Arnold College");
			returnValue.Add("Baidley College");
			returnValue.Add("Beaufort College");
			returnValue.Add("Beaumont College");
			returnValue.Add("Benison College");
			returnValue.Add("Carlyle College");
			returnValue.Add("Chaucer College");
			returnValue.Add("Courtenay College");
			returnValue.Add("Gresham College");
			returnValue.Add("Hescott College");
			returnValue.Add("Lady Matilda's College");
			returnValue.Add("Lonsdale College");
			returnValue.Add("Lovelace College");
			returnValue.Add("Mayfield College");
			returnValue.Add("Penville");
			returnValue.Add("St Gerard's Hall");
			returnValue.Add("St Jude's College");
			returnValue.Add("St Saviour's College");
			returnValue.Add("St Sebastian's College");
			returnValue.Add("Savile College");
			returnValue.Add("Trevelyan College");
			returnValue.Add("Wolsey College");
			returnValue.Add("Biblioll College");
			returnValue.Add("Cardinal College");
			returnValue.Add("Crozier College");
			returnValue.Add("Oldgate College");
			returnValue.Add("Rubric College");
			returnValue.Add("Sarcophagus College");
			returnValue.Add("Sepulchre College");
			returnValue.Add("Tudor College");
			returnValue.Add("Saint Saviour's");
			returnValue.Add("Leicester College");
			returnValue.Add("Nun's Hall");
			returnValue.Add("All Saints College");
			returnValue.Add("Apocalypse College");
			returnValue.Add("Baillie College");
			returnValue.Add("Bartlemas College");
			returnValue.Add("Bede College");
			returnValue.Add("Brazenface College");
			returnValue.Add("Cape College");
			returnValue.Add("Cardinal College");
			returnValue.Add("Charsley College");
			returnValue.Add("Clapperton College");
			returnValue.Add("Episcopus College");
			returnValue.Add("Hacker College");
			returnValue.Add("Judas College");
			returnValue.Add("The King's College");
			returnValue.Add("Kingsbridge College");
			returnValue.Add("Lancaster College");
			returnValue.Add("Lazarus College");
			returnValue.Add("Magog College");
			returnValue.Add("Mandeville College");
			returnValue.Add("Old College");
			returnValue.Add("Pentecost College");
			returnValue.Add("Persephone College");
			returnValue.Add("Plymouth College");
			returnValue.Add("Raleigh College");
			returnValue.Add("St Ambrose's College");
			returnValue.Add("St Anthony's College");
			returnValue.Add("St Bride's College");
			returnValue.Add("St Christopher's College");
			returnValue.Add("St Clements College");
			returnValue.Add("St David's College");
			returnValue.Add("St Frideswide's College");
			returnValue.Add("St George's College");
			returnValue.Add("St Jerome's College");
			returnValue.Add("St Joseph's College");
			returnValue.Add("St Jude's College");
			returnValue.Add("St Matthew's College");
			returnValue.Add("St Margaret's College");
			returnValue.Add("St Mark's College");
			returnValue.Add("St Mary's College");
			returnValue.Add("St Paul's College");
			returnValue.Add("St Severin's College");
			returnValue.Add("St Sexburga's College");
			returnValue.Add("St Simeon's College");
			returnValue.Add("St Thomas' College");
			returnValue.Add("Scone College");
			returnValue.Add("Shrewsbury College");
			returnValue.Add("Simon Magus College");
			returnValue.Add("Stendell College");
			returnValue.Add("Tresingham College");
			returnValue.Add("Warlock College");
			returnValue.Add("Shmuel Yosef Agnon");
			returnValue.Add("Kingsley Amis");
			returnValue.Add("Dorothy Baker");
			returnValue.Add("John Barth");
			returnValue.Add("Max Beerbohm");
			returnValue.Add("Saul Bellow");
			returnValue.Add("E. F. Benson");
			returnValue.Add("E. F. Benson");
			returnValue.Add("T. C. Boyle");
			returnValue.Add("Malcolm Bradbury");
			returnValue.Add("Michael Chabon");
			returnValue.Add("Nirad C. Chaudhuri");
			returnValue.Add("Susan Choi");
			returnValue.Add("J. M. Coetzee");
			returnValue.Add("Susan Coll");
			returnValue.Add("Robertson Davies");
			returnValue.Add("Pamela Dean");
			returnValue.Add("Don DeLillo");
			returnValue.Add("Jenny Diski");
			returnValue.Add("Carl Djerassi");
			returnValue.Add("D. J. Enright");
			returnValue.Add("Richard Fariña");
			returnValue.Add("Michael Frayn");
			returnValue.Add("Stephen Fry");
			returnValue.Add("Stephen Fry");
			returnValue.Add("John Kenneth Galbraith");
			returnValue.Add("Thomas Hughes");
			returnValue.Add("Hamlet Isakhanli");
			returnValue.Add("Howard Jacobson");
			returnValue.Add("Randall Jarrell");
			returnValue.Add("Denis Johnson");
			returnValue.Add("Owen Johnson");
			returnValue.Add("Pamela Hansford Johnson");
			returnValue.Add("Chip Kidd");
			returnValue.Add("Neil LaBute");
			returnValue.Add("Philip Larkin");
			returnValue.Add("Will Lavender");
			returnValue.Add("David Leavitt");
			returnValue.Add("Elinor Lipman");
			returnValue.Add("David Lodge");
			returnValue.Add("Alison Lurie");
			returnValue.Add("Mary McCarthy");
			returnValue.Add("Bernard Malamud");
			returnValue.Add("Percy Marks");
			returnValue.Add("William Hurrell Mallock");
			returnValue.Add("David Mamet");
			returnValue.Add("Javier Marías");
			returnValue.Add("Niq Mhlongo");
			returnValue.Add("Jeffrey Moore");
			returnValue.Add("Dhan Gopal Mukerji");
			returnValue.Add("Vladimir Nabokov");
			returnValue.Add("David Nicholls; Starter for Ten");
			returnValue.Add("Charles Gilman Norris");
			returnValue.Add("Joyce Carol Oates");
			returnValue.Add("John O'Hara");
			returnValue.Add("Tim Parks");
			returnValue.Add("Adrian Jones Pearson");
			returnValue.Add("Tom Perrotta");
			returnValue.Add("Francine Prose");
			returnValue.Add("Ellery Queen");
			returnValue.Add("Roger Rosenblatt");
			returnValue.Add("Philip Roth");
			returnValue.Add("Willy Russell");
			returnValue.Add("Richard Russo");
			returnValue.Add("Dorothy L. Sayers");
			returnValue.Add("Dietrich Schwanitz:[15] Der Campus");
			returnValue.Add("Tom Sharpe");
			returnValue.Add("Jane Smiley");
			returnValue.Add("Zadie Smith");
			returnValue.Add("C P Snow");
			returnValue.Add("Tammar Stein");
			returnValue.Add("Neal Stephenson");
			returnValue.Add("J. I. M. Stewart");
			returnValue.Add("Ivo Stourton");
			returnValue.Add("Ron Suskind");
			returnValue.Add("Donna Tartt");
			returnValue.Add("Sergio Troncoso");
			returnValue.Add("Evelyn Waugh");
			returnValue.Add("Hillary Waugh");
			returnValue.Add("Jean Webster");
			returnValue.Add("Paul West");
			returnValue.Add("Michael Wilding");
			returnValue.Add("John Williams");
			returnValue.Add("Angus Wilson");
			returnValue.Add("Tom Wolfe");
			returnValue.Add("Sylvia Hart Wright");
			returnValue.Add("Laurel Zuckerman");
			returnValue.Add("University of Bantshire");
			returnValue.Add("Borchester University");
			returnValue.Add("The University of Bums on Seats");
			returnValue.Add("Burston Central University");
			returnValue.Add("University of Burston");
			returnValue.Add("Christminster University");
			returnValue.Add("Clyde University");
			returnValue.Add("University of Edgestow");
			returnValue.Add("Felpersham University");
			returnValue.Add("Fibchester University");
			returnValue.Add("University of Gallifrey");
			returnValue.Add("University of Gloucester");
			returnValue.Add("University of Hilldene");
			returnValue.Add("University of Inverdoon");
			returnValue.Add("King's University");
			returnValue.Add("Kirke University");
			returnValue.Add("University College Limerick");
			returnValue.Add("Lowlands University");
			returnValue.Add("Manchester Medlock University");
			returnValue.Add("University of Maximegalon");
			returnValue.Add("University of North Yorkshire");
			returnValue.Add("University of Norwich");
			returnValue.Add("Poltowan University");
			returnValue.Add("Poppleton University");
			returnValue.Add("Rummidge University");
			returnValue.Add("St Luke's University");
			returnValue.Add("St Rule's University");
			returnValue.Add("St Sebastian's University");
			returnValue.Add("Scumbag College");
			returnValue.Add("Skerryvore University");
			returnValue.Add("Unseen University");
			returnValue.Add("Watermouth University");
			returnValue.Add("Wetherton University");
			returnValue.Add("Wetwang University");
			returnValue.Add("Wrottesley Polytechnic");
			returnValue.Add("University of Argo City");
			returnValue.Add("University of Astro City");
			returnValue.Add("University of Blue Valley");
			returnValue.Add("University of Blüdhaven");
			returnValue.Add("University of Borricón de Arriba");
			returnValue.Add("University of Champignac");
			returnValue.Add("University of Citrusville");
			returnValue.Add("University of Central City");
			returnValue.Add("University of Coast City");
			returnValue.Add("University of Dingburg");
			returnValue.Add("University of Doomstadt");
			returnValue.Add("University of Duckburg");
			returnValue.Add("University of Fawcett City");
			returnValue.Add("University of Fuxholzen");
			returnValue.Add("University of Greendale");
			returnValue.Add("University of Akebono City");
			returnValue.Add("University of Algonquin Bay");
			returnValue.Add("University of Allende del Sol");
			returnValue.Add("University of Agrestic");
			returnValue.Add("University of Angel Grove");
			returnValue.Add("University of Angelus");
			returnValue.Add("University of Babylon");
			returnValue.Add("University of Bay City");
			returnValue.Add("University of Beacon Hills");
			returnValue.Add("University of Bluebell");
			returnValue.Add("University of Buckhorn");
			returnValue.Add("University of Cabot Cove");
			returnValue.Add("University of Camden County");
			returnValue.Add("University of Charming");
			returnValue.Add("University of Chatswin");
			returnValue.Add("University of Chester's Mill");
			returnValue.Add("University of Cicely");
			returnValue.Add("University of Clinton Corners");
			returnValue.Add("University of Collinsport");
			returnValue.Add("University of Capeside");
			returnValue.Add("University of Creed");
			returnValue.Add("University of Crinkley Bottom");
			returnValue.Add("University of Dog River");
			returnValue.Add("University of Eerie");
			returnValue.Add("University of Emmerdale");
			returnValue.Add("University of Everwood");
			returnValue.Add("University of Exclamation");
			returnValue.Add("University of Fairview");
			returnValue.Add("University of Genoa City");
			returnValue.Add("University of Gotham City");
			returnValue.Add("University of Happiness");
			returnValue.Add("University of Hawkins");
			returnValue.Add("University of Holby");
			returnValue.Add("University of Hollyoaks");
			returnValue.Add("University of Jericho");
			returnValue.Add("University of Kaldor City");
			returnValue.Add("University of Lapataganj");
			returnValue.Add("University of Letherbridge");
			returnValue.Add("University of Little Dimpton");
			returnValue.Add("University of Llanview");
			returnValue.Add("University of Mega City");
			returnValue.Add("University of Mayberry");
			returnValue.Add("University of Melonville");
			returnValue.Add("University of Mystic Falls");
			returnValue.Add("University of National City");
			returnValue.Add("University of Neptune");
			returnValue.Add("University of New Canaan");
			returnValue.Add("University of Oakdale");
			returnValue.Add("University of Orson");
			returnValue.Add("University of Paradise");
			returnValue.Add("University of Pawnee");
			returnValue.Add("University of Pine Valley");
			returnValue.Add("University of Port Charles");
			returnValue.Add("University of Port Niranda");
			returnValue.Add("University of Puerto del Santos");
			returnValue.Add("University of Rosewood");
			returnValue.Add("University of Royston Vasey");
			returnValue.Add("University of Sandicot");
			returnValue.Add("University of Smallville");
			returnValue.Add("University of Springfield");
			returnValue.Add("University of Stafford");
			returnValue.Add("University of Stars Hollow");
			returnValue.Add("University of St-Jean-De-Bosco");
			returnValue.Add("University of Star City");
			returnValue.Add("University of Storybrooke");
			returnValue.Add("University of Summer Bay");
			returnValue.Add("University of Sunnydale");
			returnValue.Add("University of Twin Peaks");
			returnValue.Add("University of Walmington-on-Sea");
			returnValue.Add("University of Wayward Pines");
			returnValue.Add("University of Weatherfield");
			returnValue.Add("University of The Village");
			returnValue.Add("University of Voltafiore");
			returnValue.Add("University of Webster");
			returnValue.Add("University of Winden");
			returnValue.Add("University of Absurdistan");
			returnValue.Add("University of Abuddin");
			returnValue.Add("University of Adjikistan");
			returnValue.Add("University of Atchoo");
			returnValue.Add("University of Al Quolanudar");
			returnValue.Add("University of Aldorria");
			returnValue.Add("University of Aldovia");
			returnValue.Add("University of Alvonia");
			returnValue.Add("University of Almaigne");
			returnValue.Add("University of Altis and Stratis");
			returnValue.Add("University of Ambrosia");
			returnValue.Add("University of Americas");
			returnValue.Add("University of Amestris");
			returnValue.Add("University of Anchuria");
			returnValue.Add("University of Angosia");
			returnValue.Add("University of Angrezi Raj");
			returnValue.Add("University of Annexia");
			returnValue.Add("University of Antegria");
			returnValue.Add("University of Arendelle");
			returnValue.Add("University of Arstotzka");
			returnValue.Add("University of Arulco");
			returnValue.Add("University of Aslerfan");
			returnValue.Add("University of Atlantis");
			returnValue.Add("University of Auradon");
			returnValue.Add("University of Auroa Archipelago");
			returnValue.Add("University of Azmenistan");
			returnValue.Add("University of Axphain");
			returnValue.Add("University of Babar's Kingdom");
			returnValue.Add("University of Bacteria");
			returnValue.Add("University of Bahari");
			returnValue.Add("University of Bahavia");
			returnValue.Add("University of Baltish");
			returnValue.Add("University of Bandara");
			returnValue.Add("University of Bandiaterra");
			returnValue.Add("University of Bandrika");
			returnValue.Add("University of Bangalla");
			returnValue.Add("University of Bangistan");
			returnValue.Add("University of Banoi Archipelago");
			returnValue.Add("University of Baracas");
			returnValue.Add("University of Barama");
			returnValue.Add("University of Bartovia");
			returnValue.Add("University of Basenji");
			returnValue.Add("University of Bashkortostan");
			returnValue.Add("University of Basran");
			returnValue.Add("University of Bekkastan");
			returnValue.Add("University of Belavia");
			returnValue.Add("University of Belgravia");
			returnValue.Add("University of Beninia");
			returnValue.Add("University of Bernai Island");
			returnValue.Add("University of Berzerkistan");
			returnValue.Add("University of Besźel");
			returnValue.Add("University of Ben Fero Republic");
			returnValue.Add("University of Bialya");
			returnValue.Add("University of Blefuscu");
			returnValue.Add("University of Bolumbia");
			returnValue.Add("University of Boñigolandia");
			returnValue.Add("University of Borduria");
			returnValue.Add("University of Borostyria");
			returnValue.Add("University of Borginia");
			returnValue.Add("University of Bowser's Kingdom");
			returnValue.Add("University of Bozatta");
			returnValue.Add("University of Braganza");
			returnValue.Add("University of British States of America");
			returnValue.Add("University of Brobdingnag");
			returnValue.Add("University of Brungaria");
			returnValue.Add("University of Bruzundanga");
			returnValue.Add("University of Buchistan");
			returnValue.Add("University of Bufferia");
			returnValue.Add("University of Bultan");
			returnValue.Add("University of Buenaventura");
			returnValue.Add("University of Buranda");
			returnValue.Add("University of Cagliostro");
			returnValue.Add("University of Calbia");
			returnValue.Add("University of Caledonia");
			returnValue.Add("University of Carbombya");
			returnValue.Add("University of Carjackistan");
			returnValue.Add("University of Carovia");
			returnValue.Add("University of Carpania");
			returnValue.Add("University of Carpathia");
			returnValue.Add("University of Cascadia");
			returnValue.Add("University of Chernarus");
			returnValue.Add("University of Chinese Federation");
			returnValue.Add("University of Chula");
			returnValue.Add("University of Cobra Island");
			returnValue.Add("University of Congaree Socialist Republic");
			returnValue.Add("University of Country of the Blind");
			returnValue.Add("University of Coalition States");
			returnValue.Add("University of Concordia");
			returnValue.Add("University of University of Cobrastan");
			returnValue.Add("University of Cordinia");
			returnValue.Add("University of Corona");
			returnValue.Add("University of Corto Maltese");
			returnValue.Add("University of Socialist Democratic Republic of Corteguay");
			returnValue.Add("University of Cortuguay");
			returnValue.Add("University of Costaguana");
			returnValue.Add("University of Costa Luna");
			returnValue.Add("University of Costa Gravas");
			returnValue.Add("University of Crashbania");
			returnValue.Add("University of Czervenia");
			returnValue.Add("University of Danu");
			returnValue.Add("University of Dahomalia");
			returnValue.Add("University of Datlof");
			returnValue.Add("University of Dawsbergen");
			returnValue.Add("University of Deltora");
			returnValue.Add("University of Democratic Republic of Dahum");
			returnValue.Add("University of Diamantara");
			returnValue.Add("University of Dictionopolis");
			returnValue.Add("University of Digitopolis");
			returnValue.Add("University of Dinotopia");
			returnValue.Add("University of Draka");
			returnValue.Add("University of Drusselstein");
			returnValue.Add("University of Druznia");
			returnValue.Add("University of Durhan");
			returnValue.Add("University of Derkaderkastan");
			returnValue.Add("University of Eastasia");
			returnValue.Add("University of East Hun Chiu");
			returnValue.Add("University of Ecotopia");
			returnValue.Add("University of Edonia");
			returnValue.Add("University of Elbonia");
			returnValue.Add("University of El Ohtar");
			returnValue.Add("University of Enclave");
			returnValue.Add("University of Endostan");
			returnValue.Add("University of The Environment");
			returnValue.Add("University of Equatorial Kundu");
			returnValue.Add("University of Erewhon");
			returnValue.Add("University of Estoccia");
			returnValue.Add("University of Etchechuria");
			returnValue.Add("University of Eurasia");
			returnValue.Add("University of Farfelu");
			returnValue.Add("University of Fe'ausi");
			returnValue.Add("University of Federated Commonwealths of America");
			returnValue.Add("University of Feldenberg");
			returnValue.Add("University of Flausenthurm");
			returnValue.Add("University of Florin");
			returnValue.Add("University of Fook Island");
			returnValue.Add("University of France-outre-mer");
			returnValue.Add("University of Franchia");
			returnValue.Add("University of Freedonia");
			returnValue.Add("University of Freedonia");
			returnValue.Add("University of Gafir");
			returnValue.Add("University of Garnia");
			returnValue.Add("University of Genosha");
			returnValue.Add("University of Genovia");
			returnValue.Add("University of Gérolstein");
			returnValue.Add("University of Gilead");
			returnValue.Add("University of Gindra");
			returnValue.Add("University of Glovania");
			returnValue.Add("University of Glubbdubdrib");
			returnValue.Add("University of Gondal");
			returnValue.Add("University of Gondor");
			returnValue.Add("University of Gondour");
			returnValue.Add("University of Grinlandia");
			returnValue.Add("University of Guilder");
			returnValue.Add("University of Grand Fenwick");
			returnValue.Add("University of Greater East Asia Co-Prosperity Sphere");
			returnValue.Add("University of Graustark");
			returnValue.Add("University of Gramovian Federation");
			returnValue.Add("University of Graznavia");
			returnValue.Add("University of Great Britain");
			returnValue.Add("University of University of Grenyarnia");
			returnValue.Add("University of Groland");
			returnValue.Add("University of Halla");
			returnValue.Add("University of Hav");
			returnValue.Add("University of Hidalgo");
			returnValue.Add("University of Holy Alliance");
			returnValue.Add("University of Holy Britannian Empire");
			returnValue.Add("University of Horizon Islands");
			returnValue.Add("University of Idris");
			returnValue.Add("University of Illéa");
			returnValue.Add("University of Illyria");
			returnValue.Add("University of Impor");
			returnValue.Add("University of Indocarr");
			returnValue.Add("University of Irania");
			returnValue.Add("University of Ishtar");
			returnValue.Add("University of Islandia");
			returnValue.Add("University of Isla Island");
			returnValue.Add("University of Isla Trueno");
			returnValue.Add("University of Isle of Fogg");
			returnValue.Add("University of Isthmus Republic");
			returnValue.Add("University of Jark Empire");
			returnValue.Add("University of Jalil Empire");
			returnValue.Add("University of Kadir");
			returnValue.Add("University of Kahndaq");
			returnValue.Add("University of Kallipolis");
			returnValue.Add("University of Kambezi");
			returnValue.Add("University of Kambezi");
			returnValue.Add("University of Kamistan");
			returnValue.Add("University of Kangan");
			returnValue.Add("University of Karistan");
			returnValue.Add("University of Karzhegistan");
			returnValue.Add("University of Kasnia");
			returnValue.Add("University of Kastovia");
			returnValue.Add("University of Kaukistan");
			returnValue.Add("University of Kazirstan");
			returnValue.Add("University of Kazahrus");
			returnValue.Add("University of Kashfar");
			returnValue.Add("University of Kenyopia");
			returnValue.Add("University of Kekistan");
			returnValue.Add("University of Kerplankistan");
			returnValue.Add("University of Khemed");
			returnValue.Add("University of Khura'in");
			returnValue.Add("University of Kijuju");
			returnValue.Add("University of Kinakuta");
			returnValue.Add("University of Kingdom of Wisdom");
			returnValue.Add("University of Kingdom of Loathing");
			returnValue.Add("University of Klopstokia");
			returnValue.Add("University of Kolechia");
			returnValue.Add("University of Koratvia");
			returnValue.Add("University of Kreplachistan");
			returnValue.Add("University of Krakozhia");
			returnValue.Add("University of Krastava");
			returnValue.Add("University of Krpshtskani");
			returnValue.Add("University of Kulagong");
			returnValue.Add("University of Kumranistan");
			returnValue.Add("University of Kumbolaland");
			returnValue.Add("University of Kumsa");
			returnValue.Add("University of Kunami");
			returnValue.Add("University of Kundu");
			returnValue.Add("University of Kurjikistan");
			returnValue.Add("University of Kyrat");
			returnValue.Add("University of Kyria");
			returnValue.Add("University of Latveria");
			returnValue.Add("University of Lasria");
			returnValue.Add("University of Lovitzna");
			returnValue.Add("University of Laurania");
			returnValue.Add("University of Leutonia");
			returnValue.Add("University of Lichtenburg");
			returnValue.Add("University of Lichtenslava");
			returnValue.Add("University of Lilliput");
			returnValue.Add("University of Liechtenhaus");
			returnValue.Add("University of Limberwisk");
			returnValue.Add("University of Livonia");
			returnValue.Add("University of Loompa Land");
			returnValue.Add("University of Luftnarp");
			returnValue.Add("University of Luxenstein");
			returnValue.Add("University of Lugash");
			returnValue.Add("University of Lower Slobbovia");
			returnValue.Add("University of Lyonesse");
			returnValue.Add("University of Lyrobia");
			returnValue.Add("University of Madripoor");
			returnValue.Add("University of Mahishmathi");
			returnValue.Add("University of Maldonia");
			returnValue.Add("University of Malicuria");
			returnValue.Add("University of Maltovia");
			returnValue.Add("University of Malynera");
			returnValue.Add("University of Mandorra");
			returnValue.Add("University of Marina Venetta");
			returnValue.Add("University of Marivella Islands");
			returnValue.Add("University of Markovia");
			returnValue.Add("University of Marley");
			returnValue.Add("University of Marshovia");
			returnValue.Add("University of Maru");
			returnValue.Add("University of Matobo");
			returnValue.Add("University of Maurania");
			returnValue.Add("University of Medici");
			returnValue.Add("University of Mendorra");
			returnValue.Add("University of Merania");
			returnValue.Add("University of Meropis");
			returnValue.Add("University of Meruza");
			returnValue.Add("University of Metrofulus");
			returnValue.Add("University of Molvanîa");
			returnValue.Add("University of Moldavia");
			returnValue.Add("University of Moldovakia");
			returnValue.Add("University of Moloni Republic");
			returnValue.Add("University of Momchilgrad Republic");
			returnValue.Add("University of Mombaka");
			returnValue.Add("University of Monroe Republic");
			returnValue.Add("University of Moronika");
			returnValue.Add("University of Mundania");
			returnValue.Add("University of Mushroom Kingdom");
			returnValue.Add("University of Mypos");
			returnValue.Add("University of Mikene Empire");
			returnValue.Add("University of Meeskatania");
			returnValue.Add("University of Nairomi");
			returnValue.Add("University of Nambutu");
			returnValue.Add("University of Naruba");
			returnValue.Add("University of The Nation of the American Endless");
			returnValue.Add("University of Nazi America");
			returnValue.Add("University of Nerdocrumbesia");
			returnValue.Add("University of Nevoruss");
			returnValue.Add("University of New Californian Republic");
			returnValue.Add("University of New Cumbria");
			returnValue.Add("University of New England");
			returnValue.Add("University of New Germany");
			returnValue.Add("University of New German Republic");
			returnValue.Add("University of New Orleans");
			returnValue.Add("University of New Rearendia");
			returnValue.Add("University of New Spain");
			returnValue.Add("University of Nibia");
			returnValue.Add("University of Ninjago");
			returnValue.Add("University of Nogova");
			returnValue.Add("University of Norland");
			returnValue.Add("University of Nova Africa");
			returnValue.Add("University of Novistrana");
			returnValue.Add("University of Novoselic");
			returnValue.Add("University of Norgborg");
			returnValue.Add("University of Norteguay");
			returnValue.Add("University of North American Confederacy");
			returnValue.Add("University of North American Union");
			returnValue.Add("University of Nuevo Rico");
			returnValue.Add("University of Nuku'la Atoll");
			returnValue.Add("University of Numbani");
			returnValue.Add("University of Obristan");
			returnValue.Add("University of Oceania");
			returnValue.Add("University of Octavia");
			returnValue.Add("University of Odan");
			returnValue.Add("University of OmniStat");
			returnValue.Add("University of Old Hebrides");
			returnValue.Add("University of Osean Federation");
			returnValue.Add("University of Orsinia");
			returnValue.Add("University of Osterlich");
			returnValue.Add("University of Outer Heaven");
			returnValue.Add("University of Oz");
			returnValue.Add("University of Palombia");
			returnValue.Add("University of Panau");
			returnValue.Add("University of Panem");
			returnValue.Add("University of Papir Republic");
			returnValue.Add("University of Parador");
			returnValue.Add("University of Patusan");
			returnValue.Add("University of Penguina");
			returnValue.Add("University of Petoria");
			returnValue.Add("University of Phaic Tăn");
			returnValue.Add("University of Piresia");
			returnValue.Add("University of Pobreza Republic");
			returnValue.Add("University of Poictesme");
			returnValue.Add("University of Pokolistan");
			returnValue.Add("University of Pokrovia");
			returnValue.Add("University of Polrugaria");
			returnValue.Add("University of Pomegranate");
			returnValue.Add("University of Potarneyland");
			returnValue.Add("University of Pottsylvania");
			returnValue.Add("University of Pullamawang");
			returnValue.Add("University of Qasha");
			returnValue.Add("University of Qalif");
			returnValue.Add("University of Quebec");
			returnValue.Add("University of Qumar");
			returnValue.Add("University of Qumran");
			returnValue.Add("University of Qurac");
			returnValue.Add("University of Ragaan");
			returnValue.Add("University of Rapture");
			returnValue.Add("University of Realia");
			returnValue.Add("University of Reichtenburg");
			returnValue.Add("University of Republia");
			returnValue.Add("University of Republican Union of Nigeria and Ghana");
			returnValue.Add("University of Rhelasia");
			returnValue.Add("University of Robo-Hungarian Empire");
			returnValue.Add("University of Rolisica");
			returnValue.Add("University of Romanza");
			returnValue.Add("University of Rovinia");
			returnValue.Add("University of Ruffino");
			returnValue.Add("University of Ruritania");
			returnValue.Add("University of Rusalka");
			returnValue.Add("University of Rocky Mountains States");
			returnValue.Add("University of Rook Islands");
			returnValue.Add("University of Russian Democratic Union");
			returnValue.Add("University of Sabaeus");
			returnValue.Add("University of St. George's Island");
			returnValue.Add("University of Sahrani");
			returnValue.Add("University of Saint Marie");
			returnValue.Add("University of Samavia");
			returnValue.Add("University of San Blas");
			returnValue.Add("University of San Escobar");
			returnValue.Add("University of San Esperito");
			returnValue.Add("University of Sangala");
			returnValue.Add("University of San Glucos");
			returnValue.Add("University of San Lorenzo");
			returnValue.Add("University of San Lorenzo");
			returnValue.Add("University of San Madeiro");
			returnValue.Add("University of San Marcos");
			returnValue.Add("University of San Miguel");
			returnValue.Add("University of San Salvador");
			returnValue.Add("University of San Serriffe");
			returnValue.Add("University of San Sombrèro");
			returnValue.Add("University of San Theodoros");
			returnValue.Add("University of San Pasquale");
			returnValue.Add("University of San Pedro");
			returnValue.Add("University of Santa Prisca");
			returnValue.Add("University of Santo Marco");
			returnValue.Add("University of São Rico");
			returnValue.Add("University of Saradia");
			returnValue.Add("University of Sarasa Land");
			returnValue.Add("University of Sardovia");
			returnValue.Add("University of Sarkhan");
			returnValue.Add("University of Sauville");
			returnValue.Add("University of Scandinavia");
			returnValue.Add("University of University of Seko");
			returnValue.Add("University of Selgina");
			returnValue.Add("University of Seyrun");
			returnValue.Add("University of Serdaristan");
			returnValue.Add("University of Serena Republic");
			returnValue.Add("University of Shangri-La");
			returnValue.Add("University of Shitschtorchnia");
			returnValue.Add("University of Sierra Gordo");
			returnValue.Add("University of Slaka");
			returnValue.Add("University of University of Slovetzia");
			returnValue.Add("University of Sodor");
			returnValue.Add("University of Solis");
			returnValue.Add("University of Sokovia");
			returnValue.Add("University of Soviet Unterzoegersdorf");
			returnValue.Add("University of South Africa");
			returnValue.Add("University of Spensonia");
			returnValue.Add("University of Squamuglia");
			returnValue.Add("University of Strackenz");
			returnValue.Add("University of Sultanistan");
			returnValue.Add("University of Sunda");
			returnValue.Add("University of Svenborgia");
			returnValue.Add("University of Syldavia");
			returnValue.Add("University of Sylvania");
			returnValue.Add("University of Name");
			returnValue.Add("University of Takistan");
			returnValue.Add("University of Tajinkistan");
			returnValue.Add("University of Taronia");
			returnValue.Add("University of Tazbekistan");
			returnValue.Add("University of Tcherkistan");
			returnValue.Add("University of Tecala");
			returnValue.Add("University of Tescara");
			returnValue.Add("University of The Great Fusion");
			returnValue.Add("University of Themyscira");
			returnValue.Add("University of Tibecuador");
			returnValue.Add("University of Tijata");
			returnValue.Add("University of Tirania");
			returnValue.Add("University of Trans-Carpathia");
			returnValue.Add("University of Tomainia");
			returnValue.Add("University of Transia");
			returnValue.Add("University of Tropico");
			returnValue.Add("University of Tsergovia");
			returnValue.Add("University of University of Tundrabania");
			returnValue.Add("University of Turaqistan");
			returnValue.Add("University of Turgistan");
			returnValue.Add("University of Tyranistan");
			returnValue.Add("University of Ul Qoma");
			returnValue.Add("University of University of Ugigistan");
			returnValue.Add("University of Umbutu");
			returnValue.Add("University of Unaudited Arab Emirates");
			returnValue.Add("University of The Union of The United States of America");
			returnValue.Add("University of United Federation");
			returnValue.Add("University of United Eurasian State");
			returnValue.Add("University of United Islamic Republic");
			returnValue.Add("University of Uqbar");
			returnValue.Add("University of Urk");
			returnValue.Add("University of Urkesh");
			returnValue.Add("University of Urmania");
			returnValue.Add("University of Ustinkistan");
			returnValue.Add("University of Utopia");
			returnValue.Add("University of Urzikstan");
			returnValue.Add("University of Vadeem");
			returnValue.Add("University of Val Verde");
			returnValue.Add("University of Valeska");
			returnValue.Add("University of Vermillion Kingdom");
			returnValue.Add("University of Veyshnoria");
			returnValue.Add("University of Vespugia");
			returnValue.Add("University of Vilena");
			returnValue.Add("University of Vyseni");
			returnValue.Add("University of Vulgaria");
			returnValue.Add("University of Wadiya");
			returnValue.Add("University of Wakanda");
			returnValue.Add("University of West Angola");
			returnValue.Add("University of West Hun Chiu");
			returnValue.Add("University of West Britannia");
			returnValue.Add("University of Wongnaileum");
			returnValue.Add("University of The World State");
			returnValue.Add("University of Wredpryd");
			returnValue.Add("University of Yamapalu");
			returnValue.Add("University of Yara");
			returnValue.Add("University of Yatakang");
			returnValue.Add("University of Yellow Empire");
			returnValue.Add("University of Yerba");
			returnValue.Add("University of Yewaire");
			returnValue.Add("University of Yudonia");
			returnValue.Add("University of Yinke");
			returnValue.Add("University of Zahiristan");
			returnValue.Add("University of Zahrain");
			returnValue.Add("University of Zangaro");
			returnValue.Add("University of Zanzarim");
			returnValue.Add("University of Zanzibar Land");
			returnValue.Add("University of Zekistan");
			returnValue.Add("University of Zamunda");
			returnValue.Add("University of Zubrowka");
			returnValue.Add("University of Zephyria");
			returnValue.Add("University of Zanda");
			returnValue.Add("University of Zembla");
			returnValue.Add("University of Zemenia");
			returnValue.Add("University of Zeon");
			returnValue.Add("University of Zeeskatania");
			return returnValue;
		}

	}
}